name: prosenos-backend

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - SCRAPE_FUTBOL_URL=${SCRAPE_FUTBOL_URL}
    volumes:
      - .:/app
      - /app/.venv
