name: prosenos-backend

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - SCRAPER_BASE_URL=http://futbol_scraper:8000
    volumes:
      - .:/app
      - /app/.venv
      - /app/futbol_scraper

  futbol_scraper:
    build:
      context: ./futbol_scraper
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - ./futbol_scraper:/app
      - /app/.venv
